version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  spring:
    image: maryemtayeb/achat:latest
    restart: always
    ports:
      - "8088:8087"
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url": "jdbc:mysql://db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
             "spring.datasource.username": "root",
             "spring.datasource.password": "root",
             "spring.jpa.hibernate.ddl-auto": "update"
           }'
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db_data: {}
